<CODEGEN_FILENAME><StructureNoplural>Base.dbl</CODEGEN_FILENAME>
<REQUIRES_CODEGEN_VERSION>5.4.6</REQUIRES_CODEGEN_VERSION>
;//****************************************************************************
;//
;// Title:       ODataModel.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Template to define structure based Data Object with CLR types
;//
;// Copyright (c) 2012, Synergex International, Inc. All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;;*****************************************************************************
;;
;; Title:       <StructureNoplural>Base.dbl
;;
;; Description: Data model representing data defined by the repository
;;              structure <STRUCTURE_NOALIAS><IF STRUCTURE_FILES> and from the data file <FILE_NAME></IF STRUCTURE_FILES>.
;;
;;*****************************************************************************
;; WARNING: GENERATED CODE!
;; This file was generated by CodeGen. Avoid editing the file if possible.
;; Any changes you make will be lost of the file is re-generated.
;;*****************************************************************************

import System
import System.Collections.Generic
import System.ComponentModel.DataAnnotations
import System.Text
import Harmony.Core
import Harmony.Core.Converters
<IF DEFINED_ENABLE_FIELD_SECURITY>
import Harmony.OData
</IF DEFINED_ENABLE_FIELD_SECURITY>
import Harmony.Core.Context
import Harmony.Core.FileIO
import Microsoft.Extensions.DependencyInjection

namespace <NAMESPACE>

    public partial abstract class <StructureNoplural>Base extends DataObjectBase

        ;;make the record available and a copy
        private mSynergyData, str<StructureNoplural>
        private mOriginalSynergyData, str<StructureNoplural>
        public SynergyStructure, str<StructureNoplural>
        
.region "Constructors"

        ;;; <summary>
        ;;;  Constructor, initialise the base fields
        ;;; </summary>
        public method <StructureNoplural>Base
            parent()
        proc
            init mSynergyData, mOriginalSynergyData
        endmethod

        ;;; <summary>
        ;;;  Alternate Constructor, accepts the structured data
        ;;; </summary>
        public method <StructureNoplural>Base
            required in inData, a
            required in inGrfa, a
            parent()
        proc
            mSynergyData = mOriginalSynergyData = inData
            mGlobalRFA = inGrfa
        endmethod

        ;;; <summary>
        ;;;  Return str<StructureNoplural> size
        ;;; </summary>
        public static method Get<StructureNoplural>Size ,int
        proc
            mreturn ^size(str<StructureNoplural>)
        endmethod     

.endregion

.region "Attributes of this entity"

<IF STRUCTURE_RELATIVE>
        ;;; <summary>
        ;;; Record number
        ;;; </summary>
        public readwrite property RecordNumber, int

</IF STRUCTURE_RELATIVE>
<COUNTER_1_RESET>
<FIELD_LOOP>
  <IF USER>
  <ELSE>
    <IF CUSTOM_NOT_HARMONY_EXCLUDE>
        ;;; <summary>
        ;;; <FIELD_DESC>
        ;;; </summary>
      <COUNTER_1_INCREMENT>
      <IF HARMONYCORE_CUSTOM_FIELD>
        protected property Sd<FieldSqlname>, <HARMONYCORE_FIELD_DATATYPE>
      <ELSE>
        protected property Sd<FieldSqlname>, <FIELD_TYPE>
      </IF HARMONYCORE_CUSTOM_FIELD>
            method get
            proc
                mreturn mSynergyData.<field_original_name_modified>             
            endmethod
            method set
            proc
      <IF DEFINED_ENABLE_READ_ONLY_PROPERTIES>
        <IF READONLY>
                throw new ApplicationException("Property <FieldSqlname> is read only!")
        </IF READONLY>
      </IF DEFINED_ENABLE_READ_ONLY_PROPERTIES> 
                mSynergyData.<field_original_name_modified> = value               
            endmethod
        endproperty

    </IF CUSTOM_NOT_HARMONY_EXCLUDE>
  </IF USER>
</FIELD_LOOP>
.endregion


.region "Other attributes"

        ;;; <summary>
        ;;; Expose the complete synergy record
        ;;; </summary>
        public override property SynergyRecord, a
            method get
            proc
                mreturn mSynergyData
            endmethod
        endproperty

        ;;; <summary>
        ;;; Expose the complete original synergy record
        ;;; </summary>
        public override property OriginalSynergyRecord, a
            method get
            proc
                mreturn mOriginalSynergyData
            endmethod
        endproperty

.endregion

.region "Public methods"

        ;;; <summary>
        ;;;
        ;;; </summary>
        public override method InternalSynergyRecord, void
            targetMethod, @AlphaAction
        proc
            targetMethod(mSynergyData, mGlobalRFA)
        endmethod

        ;;; <summary>
        ;;; Allow the host to validate all fields. Each field will fire the validation method.
        ;;; </summary>
        public override method InitialValidateData, void
        proc
        endmethod

        ;;; <summary>
        ;;;
        ;;; </summary>
        public override method InternalGetValues, [#]@object
        proc
            ;;TODO: This should be returning boxed values for each of our fields
            mreturn new Object[<COUNTER_1_VALUE>]
        endmethod

;//
;// ==========================================================================================
;// RUNTIME VALIDATION FOR RELATIONS
;//
<IF DEFINED_ENABLE_RELATIONS>
  <IF STRUCTURE_RELATIONS>
;//
        ;;; <summary>
        ;;; Validate data for one-to-one relations
        ;;; </summary>
        ;;; <param name="type">Validation type (create, update or delete)</param>
        ;;; <param name="sp">Serices provider</param>
        public override method Validate, void
            required in vType, ValidationType
            required in sp, @IServiceProvider
    <RELATION_LOOP_RESTRICTED>

            ;;From key for <HARMONYCORE_RELATION_NAME>
            record rel<RELATION_NUMBER>FromKey
      <COUNTER_1_RESET>
      <FROM_KEY_SEGMENT_LOOP>
        <IF SEG_TYPE_FIELD>
              <segment_name>, <segment_spec>
        </IF SEG_TYPE_FIELD>
        <IF SEG_TYPE_LITERAL>
          <COUNTER_1_INCREMENT>
              litseg<COUNTER_1_VALUE>, a*, "<SEGMENT_LITVAL>"
        </IF SEG_TYPE_LITERAL>
      </FROM_KEY_SEGMENT_LOOP>
            endrecord
    </RELATION_LOOP_RESTRICTED>
        proc
            ;;No relation validation if the record is being deleted
            if (vType == ValidationType.Delete)
                mreturn

            ;;Get an instance of IDataObjectProvider
            data doProvider, @IDataObjectProvider, sp.GetService<IDataObjectProvider>()

    <RELATION_LOOP_RESTRICTED>
            ;;--------------------------------------------------------------------------------
            ;;Validate data for relation <RELATION_NUMBER> (<HARMONYCORE_RELATION_NAME>)

      <IF REQUIRES_MATCH>
        <COUNTER_1_RESET>
        <FROM_KEY_SEGMENT_LOOP>
          <IF SEG_TYPE_FIELD>
            rel<RELATION_NUMBER>FromKey.<segment_name> = mSynergyData.<segment_name>
          <ELSE>
            <IF SEG_TYPE_LITERAL>
            <COUNTER_1_INCREMENT>
            rel<RELATION_NUMBER>FromKey.litseg<COUNTER_1_VALUE> = "<SEGMENT_LITVAL>"
            </IF SEG_TYPE_LITERAL>
          </IF SEG_TYPE_FIELD>
        </FROM_KEY_SEGMENT_LOOP>
            relFromKeyValidate<RelationTostructureNoplural>(doProvider,<TO_KEY_NUMBER>,rel<RELATION_NUMBER>FromKey)
      <ELSE>
            ;;This relation does not REQUIRE a match in the target file.
      </IF REQUIRES_MATCH>

    </RELATION_LOOP_RESTRICTED>

            ;;If we have a ValidateCustom method, call it
            ValidateCustom(vType,sp)

        endmethod
        
    <RELATION_LOOP_RESTRICTED>
      <IF REQUIRES_MATCH>
        protected abstract method relFromKeyValidate<RelationTostructureNoplural> ,void
            required in doProvider  ,@IDataObjectProvider
            required in keyNumber   ,n
            required in rel<RELATION_NUMBER>FromKey  ,a
        proc
        endmethod
        
      </IF REQUIRES_MATCH>
    </RELATION_LOOP_RESTRICTED>

  <ELSE>
        ;;; <summary>
        ;;; Validate data
        ;;; </summary>
        ;;; <param name="type">Validation type (create, update or delete)</param>
        ;;; <param name="sp">Serices provider</param>
        public override method Validate, void
            required in vType, ValidationType
            required in sp, @IServiceProvider
        proc
            ;;If we have a ValidateCustom method, call it
            ValidateCustom(vType,sp)
        endmethod

  </IF STRUCTURE_RELATIONS>
</IF DEFINED_ENABLE_RELATIONS>

        private partial method ValidateCustom, void
            required in vType, ValidationType
            required in sp, @IServiceProvider
        endmethod

;// ==========================================================================================
.endregion
;//
;// Relations
;//
<IF DEFINED_ENABLE_RELATIONS>
  <IF STRUCTURE_RELATIONS>
;//
;//
;//
    <COUNTER_2_RESET>
    <RELATION_LOOP_RESTRICTED>
      <COUNTER_1_RESET>
      <FROM_KEY_SEGMENT_LOOP>
        <IF SEG_TYPE_LITERAL>
          <COUNTER_2_INCREMENT>
            <IF COUNTER_2_EQ_1>

.region "Properties to represent literal key segments"

            </IF COUNTER_2_EQ_1>
        ;;; <summary>
        ;;;
        ;;; </summary>
        public readonly property <RelationFromkey>Literal<COUNTER_1_INCREMENT><COUNTER_1_VALUE>, <LITERAL_SEGMENT_SNTYPE>, <LITERAL_SEGMENT_VALUE>
        private _<RelationFromkey>Literal<COUNTER_1_VALUE>, <LITERAL_SEGMENT_SNTYPE>, <LITERAL_SEGMENT_VALUE>
        </IF SEG_TYPE_LITERAL>
      </FROM_KEY_SEGMENT_LOOP>
    </RELATION_LOOP_RESTRICTED>
    <IF COUNTER_2_GT_0>

.endregion

    </IF COUNTER_2_GT_0>
  </IF STRUCTURE_RELATIONS>
</IF DEFINED_ENABLE_RELATIONS>

endclass

endnamespace
